/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WatcherRouteImport } from './routes/watcher'
import { Route as UsersRouteImport } from './routes/users'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as ChaptersRouteImport } from './routes/chapters'
import { Route as BookmarksRouteImport } from './routes/bookmarks'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UUsernameRouteImport } from './routes/u.$username'
import { Route as ChatSlugRouteImport } from './routes/chat.$slug'
import { Route as ChaptersSlugRouteImport } from './routes/chapters.$slug'
import { Route as AdminWatcherRouteImport } from './routes/admin.watcher'
import { Route as ApiWatcherTtsRouteImport } from './routes/api/watcher.tts'
import { Route as ApiWatcherChatRouteImport } from './routes/api/watcher.chat'

const WatcherRoute = WatcherRouteImport.update({
  id: '/watcher',
  path: '/watcher',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaptersRoute = ChaptersRouteImport.update({
  id: '/chapters',
  path: '/chapters',
  getParentRoute: () => rootRouteImport,
} as any)
const BookmarksRoute = BookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatSlugRoute = ChatSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ChatRoute,
} as any)
const ChaptersSlugRoute = ChaptersSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ChaptersRoute,
} as any)
const AdminWatcherRoute = AdminWatcherRouteImport.update({
  id: '/watcher',
  path: '/watcher',
  getParentRoute: () => AdminRoute,
} as any)
const ApiWatcherTtsRoute = ApiWatcherTtsRouteImport.update({
  id: '/api/watcher/tts',
  path: '/api/watcher/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWatcherChatRoute = ApiWatcherChatRouteImport.update({
  id: '/api/watcher/chat',
  path: '/api/watcher/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/bookmarks': typeof BookmarksRoute
  '/chapters': typeof ChaptersRouteWithChildren
  '/chat': typeof ChatRouteWithChildren
  '/profile': typeof ProfileRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/users': typeof UsersRoute
  '/watcher': typeof WatcherRoute
  '/admin/watcher': typeof AdminWatcherRoute
  '/chapters/$slug': typeof ChaptersSlugRoute
  '/chat/$slug': typeof ChatSlugRoute
  '/u/$username': typeof UUsernameRoute
  '/api/watcher/chat': typeof ApiWatcherChatRoute
  '/api/watcher/tts': typeof ApiWatcherTtsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/bookmarks': typeof BookmarksRoute
  '/chapters': typeof ChaptersRouteWithChildren
  '/chat': typeof ChatRouteWithChildren
  '/profile': typeof ProfileRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/users': typeof UsersRoute
  '/watcher': typeof WatcherRoute
  '/admin/watcher': typeof AdminWatcherRoute
  '/chapters/$slug': typeof ChaptersSlugRoute
  '/chat/$slug': typeof ChatSlugRoute
  '/u/$username': typeof UUsernameRoute
  '/api/watcher/chat': typeof ApiWatcherChatRoute
  '/api/watcher/tts': typeof ApiWatcherTtsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/bookmarks': typeof BookmarksRoute
  '/chapters': typeof ChaptersRouteWithChildren
  '/chat': typeof ChatRouteWithChildren
  '/profile': typeof ProfileRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/users': typeof UsersRoute
  '/watcher': typeof WatcherRoute
  '/admin/watcher': typeof AdminWatcherRoute
  '/chapters/$slug': typeof ChaptersSlugRoute
  '/chat/$slug': typeof ChatSlugRoute
  '/u/$username': typeof UUsernameRoute
  '/api/watcher/chat': typeof ApiWatcherChatRoute
  '/api/watcher/tts': typeof ApiWatcherTtsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/bookmarks'
    | '/chapters'
    | '/chat'
    | '/profile'
    | '/sitemap.xml'
    | '/users'
    | '/watcher'
    | '/admin/watcher'
    | '/chapters/$slug'
    | '/chat/$slug'
    | '/u/$username'
    | '/api/watcher/chat'
    | '/api/watcher/tts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/bookmarks'
    | '/chapters'
    | '/chat'
    | '/profile'
    | '/sitemap.xml'
    | '/users'
    | '/watcher'
    | '/admin/watcher'
    | '/chapters/$slug'
    | '/chat/$slug'
    | '/u/$username'
    | '/api/watcher/chat'
    | '/api/watcher/tts'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/bookmarks'
    | '/chapters'
    | '/chat'
    | '/profile'
    | '/sitemap.xml'
    | '/users'
    | '/watcher'
    | '/admin/watcher'
    | '/chapters/$slug'
    | '/chat/$slug'
    | '/u/$username'
    | '/api/watcher/chat'
    | '/api/watcher/tts'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  BookmarksRoute: typeof BookmarksRoute
  ChaptersRoute: typeof ChaptersRouteWithChildren
  ChatRoute: typeof ChatRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  UsersRoute: typeof UsersRoute
  WatcherRoute: typeof WatcherRoute
  UUsernameRoute: typeof UUsernameRoute
  ApiWatcherChatRoute: typeof ApiWatcherChatRoute
  ApiWatcherTtsRoute: typeof ApiWatcherTtsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/watcher': {
      id: '/watcher'
      path: '/watcher'
      fullPath: '/watcher'
      preLoaderRoute: typeof WatcherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters': {
      id: '/chapters'
      path: '/chapters'
      fullPath: '/chapters'
      preLoaderRoute: typeof ChaptersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookmarks': {
      id: '/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof BookmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$slug': {
      id: '/chat/$slug'
      path: '/$slug'
      fullPath: '/chat/$slug'
      preLoaderRoute: typeof ChatSlugRouteImport
      parentRoute: typeof ChatRoute
    }
    '/chapters/$slug': {
      id: '/chapters/$slug'
      path: '/$slug'
      fullPath: '/chapters/$slug'
      preLoaderRoute: typeof ChaptersSlugRouteImport
      parentRoute: typeof ChaptersRoute
    }
    '/admin/watcher': {
      id: '/admin/watcher'
      path: '/watcher'
      fullPath: '/admin/watcher'
      preLoaderRoute: typeof AdminWatcherRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/watcher/tts': {
      id: '/api/watcher/tts'
      path: '/api/watcher/tts'
      fullPath: '/api/watcher/tts'
      preLoaderRoute: typeof ApiWatcherTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/watcher/chat': {
      id: '/api/watcher/chat'
      path: '/api/watcher/chat'
      fullPath: '/api/watcher/chat'
      preLoaderRoute: typeof ApiWatcherChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminWatcherRoute: typeof AdminWatcherRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminWatcherRoute: AdminWatcherRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ChaptersRouteChildren {
  ChaptersSlugRoute: typeof ChaptersSlugRoute
}

const ChaptersRouteChildren: ChaptersRouteChildren = {
  ChaptersSlugRoute: ChaptersSlugRoute,
}

const ChaptersRouteWithChildren = ChaptersRoute._addFileChildren(
  ChaptersRouteChildren,
)

interface ChatRouteChildren {
  ChatSlugRoute: typeof ChatSlugRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatSlugRoute: ChatSlugRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  BookmarksRoute: BookmarksRoute,
  ChaptersRoute: ChaptersRouteWithChildren,
  ChatRoute: ChatRouteWithChildren,
  ProfileRoute: ProfileRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  UsersRoute: UsersRoute,
  WatcherRoute: WatcherRoute,
  UUsernameRoute: UUsernameRoute,
  ApiWatcherChatRoute: ApiWatcherChatRoute,
  ApiWatcherTtsRoute: ApiWatcherTtsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
